"""init

Revision ID: 146d72820e7c
Revises: 
Create Date: 2020-04-08 13:43:58.104723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146d72820e7c'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('name', name=op.f('uq_users_name'))
    )
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_scenarios_creator_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenarios'))
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('next', sa.Integer(), nullable=True),
    sa.Column('previous', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_items_creator_id_users')),
    sa.ForeignKeyConstraint(['next'], ['items.id'], name=op.f('fk_items_next_items')),
    sa.ForeignKeyConstraint(['previous'], ['items.id'], name=op.f('fk_items_previous_items')),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_items_scenario_id_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    op.drop_table('scenarios')
    op.drop_table('users')
    # ### end Alembic commands ###
